-- Nest Student Notes Supabase schema. Run once in the Supabase SQL Editor.
-- The application accesses these tables from its server with a server-only
-- Supabase secret key. Browser access is denied by RLS.
create table if not exists public.users (
  id text primary key,
  google_id text not null unique,
  email text not null,
  name text not null default '',
  picture text,
  email_verified boolean not null default false,
  created_at timestamptz not null default now(),
  last_login timestamptz not null default now(),
  full_name text,
  contact_email text,
  role text not null default 'Student',
  profile_completed boolean not null default false
);
create table if not exists public.sessions (
  token_hash text primary key,
  user_id text not null references public.users(id) on delete cascade,
  expires_at bigint not null
);
create table if not exists public.oauth_states (
  token_hash text primary key,
  verifier text not null,
  expires_at bigint not null
);
create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id text not null references public.users(id) on delete cascade,
  title text not null,
  original_name text not null,
  stored_name text not null unique,
  mime_type text,
  size_bytes bigint not null,
  created_at timestamptz not null default now()
);
create table if not exists public.text_notes (
  id bigint generated by default as identity primary key,
  user_id text not null references public.users(id) on delete cascade,
  title text not null,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  user_id text not null references public.users(id) on delete cascade,
  text text not null,
  completed boolean not null default false,
  due_at timestamptz,
  created_at timestamptz not null default now()
);
alter table public.todos add column if not exists due_at timestamptz;
create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  user_id text references public.users(id) on delete set null,
  event_type text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists sessions_user_expiry_idx on public.sessions(user_id, expires_at);
create index if not exists notes_user_created_idx on public.notes(user_id, created_at desc);
create index if not exists text_notes_user_created_idx on public.text_notes(user_id, created_at desc);
create index if not exists todos_user_created_idx on public.todos(user_id, created_at desc);
create index if not exists activity_user_created_idx on public.activity_log(user_id, created_at desc);

alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.oauth_states enable row level security;
alter table public.notes enable row level security;
alter table public.text_notes enable row level security;
alter table public.todos enable row level security;
alter table public.activity_log enable row level security;

insert into storage.buckets (id, name, public, file_size_limit)
values ('student-notes', 'student-notes', false, 10485760)
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit;
