-- Nest Student Notes Supabase schema. Run once in the Supabase SQL Editor.
-- The application accesses these tables from its server with a server-only
-- Supabase secret key. Browser access is denied by RLS.
create table if not exists public.users (
  id text primary key,
  google_id text not null unique,
  email text not null,
  name text not null default '',
  picture text,
  email_verified boolean not null default false,
  created_at timestamptz not null default now(),
  last_login timestamptz not null default now(),
  full_name text,
  contact_email text,
  role text not null default 'Student',
  profile_completed boolean not null default false
);
create table if not exists public.sessions (
  token_hash text primary key,
  user_id text not null references public.users(id) on delete cascade,
  expires_at bigint not null
);
create table if not exists public.oauth_states (
  token_hash text primary key,
  verifier text not null,
  expires_at bigint not null
);
create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id text not null references public.users(id) on delete cascade,
  title text not null,
  original_name text not null,
  stored_name text not null unique,
  mime_type text,
  size_bytes bigint not null,
  created_at timestamptz not null default now()
);
create table if not exists public.text_notes (
  id bigint generated by default as identity primary key,
  user_id text not null references public.users(id) on delete cascade,
  title text not null,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.public_posts (
  id bigint generated by default as identity primary key,
  author_id text not null references public.users(id) on delete cascade,
  title text not null check (char_length(title) <= 120),
  content text not null check (char_length(content) <= 10000),
  like_count bigint not null default 0 check (like_count >= 0),
  comment_count bigint not null default 0 check (comment_count >= 0),
  repost_count bigint not null default 0 check (repost_count >= 0),
  created_at timestamptz not null default now()
);
create table if not exists public.public_post_attachments (
  post_id bigint primary key references public.public_posts(id) on delete cascade,
  original_name text not null check (char_length(original_name) <= 180),
  storage_name text not null unique,
  content_type text not null check (content_type in (
    'image/png', 'image/jpeg', 'image/webp', 'image/gif', 'application/pdf',
    'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'text/plain'
  )),
  size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 10485760),
  created_at timestamptz not null default now()
);
create table if not exists public.public_post_likes (
  post_id bigint not null references public.public_posts(id) on delete cascade,
  user_id text not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);
create table if not exists public.public_post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.public_posts(id) on delete cascade,
  author_id text not null references public.users(id) on delete cascade,
  content text not null check (char_length(content) <= 1000),
  created_at timestamptz not null default now()
);
create table if not exists public.public_post_reposts (
  post_id bigint not null references public.public_posts(id) on delete cascade,
  user_id text not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);
create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  user_id text not null references public.users(id) on delete cascade,
  text text not null,
  completed boolean not null default false,
  due_at timestamptz,
  created_at timestamptz not null default now()
);
alter table public.todos add column if not exists due_at timestamptz;
create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  user_id text references public.users(id) on delete set null,
  event_type text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists sessions_user_expiry_idx on public.sessions(user_id, expires_at);
create index if not exists notes_user_created_idx on public.notes(user_id, created_at desc);
create index if not exists text_notes_user_created_idx on public.text_notes(user_id, created_at desc);
create index if not exists public_posts_created_idx on public.public_posts(created_at desc);
create index if not exists public_post_likes_user_idx on public.public_post_likes(user_id, post_id);
create index if not exists public_post_comments_created_idx on public.public_post_comments(post_id, created_at);
create index if not exists public_post_reposts_user_idx on public.public_post_reposts(user_id, post_id);
create index if not exists todos_user_created_idx on public.todos(user_id, created_at desc);
create index if not exists activity_user_created_idx on public.activity_log(user_id, created_at desc);

update public.public_posts p set
  like_count = (select count(*) from public.public_post_likes l where l.post_id = p.id),
  comment_count = (select count(*) from public.public_post_comments c where c.post_id = p.id),
  repost_count = (select count(*) from public.public_post_reposts r where r.post_id = p.id);

alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.oauth_states enable row level security;
alter table public.notes enable row level security;
alter table public.text_notes enable row level security;
alter table public.public_posts enable row level security;
alter table public.public_post_attachments enable row level security;
alter table public.public_post_likes enable row level security;
alter table public.public_post_comments enable row level security;
alter table public.public_post_reposts enable row level security;
alter table public.todos enable row level security;
alter table public.activity_log enable row level security;

insert into storage.buckets (id, name, public, file_size_limit)
values ('student-notes', 'student-notes', false, 10485760)
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit;

create or replace function public.sync_social_post_counters()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_post_id bigint;
  amount integer;
begin
  if tg_op = 'DELETE' then
    target_post_id := old.post_id;
    amount := -1;
  else
    target_post_id := new.post_id;
    amount := 1;
  end if;

  if tg_table_name = 'public_post_likes' then
    update public.public_posts set like_count = greatest(like_count + amount, 0) where id = target_post_id;
  elsif tg_table_name = 'public_post_comments' then
    update public.public_posts set comment_count = greatest(comment_count + amount, 0) where id = target_post_id;
  elsif tg_table_name = 'public_post_reposts' then
    update public.public_posts set repost_count = greatest(repost_count + amount, 0) where id = target_post_id;
  end if;

  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$$;

drop trigger if exists public_post_likes_counter on public.public_post_likes;
create trigger public_post_likes_counter after insert or delete on public.public_post_likes
for each row execute function public.sync_social_post_counters();
drop trigger if exists public_post_comments_counter on public.public_post_comments;
create trigger public_post_comments_counter after insert or delete on public.public_post_comments
for each row execute function public.sync_social_post_counters();
drop trigger if exists public_post_reposts_counter on public.public_post_reposts;
create trigger public_post_reposts_counter after insert or delete on public.public_post_reposts
for each row execute function public.sync_social_post_counters();
