-- Public student notes, likes, comments, reposts, and cached counters.
-- Run once in the existing Supabase project's SQL Editor. Safe to rerun.

create table if not exists public.public_posts (
  id bigint generated by default as identity primary key,
  author_id text not null references public.users(id) on delete cascade,
  title text not null check (char_length(title) <= 120),
  content text not null check (char_length(content) <= 10000),
  like_count bigint not null default 0 check (like_count >= 0),
  comment_count bigint not null default 0 check (comment_count >= 0),
  repost_count bigint not null default 0 check (repost_count >= 0),
  created_at timestamptz not null default now()
);

alter table public.public_posts add column if not exists like_count bigint not null default 0;
alter table public.public_posts add column if not exists comment_count bigint not null default 0;
alter table public.public_posts add column if not exists repost_count bigint not null default 0;

create table if not exists public.public_post_likes (
  post_id bigint not null references public.public_posts(id) on delete cascade,
  user_id text not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.public_post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.public_posts(id) on delete cascade,
  author_id text not null references public.users(id) on delete cascade,
  content text not null check (char_length(content) <= 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.public_post_reposts (
  post_id bigint not null references public.public_posts(id) on delete cascade,
  user_id text not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create index if not exists public_posts_created_idx on public.public_posts(created_at desc);
create index if not exists public_post_likes_user_idx on public.public_post_likes(user_id, post_id);
create index if not exists public_post_comments_created_idx on public.public_post_comments(post_id, created_at);
create index if not exists public_post_reposts_user_idx on public.public_post_reposts(user_id, post_id);

update public.public_posts p set
  like_count = (select count(*) from public.public_post_likes l where l.post_id = p.id),
  comment_count = (select count(*) from public.public_post_comments c where c.post_id = p.id),
  repost_count = (select count(*) from public.public_post_reposts r where r.post_id = p.id);

alter table public.public_posts enable row level security;
alter table public.public_post_likes enable row level security;
alter table public.public_post_comments enable row level security;
alter table public.public_post_reposts enable row level security;

create or replace function public.sync_social_post_counters()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_post_id bigint;
  amount integer;
begin
  if tg_op = 'DELETE' then
    target_post_id := old.post_id;
    amount := -1;
  else
    target_post_id := new.post_id;
    amount := 1;
  end if;

  if tg_table_name = 'public_post_likes' then
    update public.public_posts set like_count = greatest(like_count + amount, 0) where id = target_post_id;
  elsif tg_table_name = 'public_post_comments' then
    update public.public_posts set comment_count = greatest(comment_count + amount, 0) where id = target_post_id;
  elsif tg_table_name = 'public_post_reposts' then
    update public.public_posts set repost_count = greatest(repost_count + amount, 0) where id = target_post_id;
  end if;

  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$$;

drop trigger if exists public_post_likes_counter on public.public_post_likes;
create trigger public_post_likes_counter after insert or delete on public.public_post_likes
for each row execute function public.sync_social_post_counters();
drop trigger if exists public_post_comments_counter on public.public_post_comments;
create trigger public_post_comments_counter after insert or delete on public.public_post_comments
for each row execute function public.sync_social_post_counters();
drop trigger if exists public_post_reposts_counter on public.public_post_reposts;
create trigger public_post_reposts_counter after insert or delete on public.public_post_reposts
for each row execute function public.sync_social_post_counters();
